name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run spotless check
        run: ./gradlew spotlessCheck

      - name: Run compileKotlin
        run: ./gradlew compileKotlin

      - name: Run unit tests
        run: ./gradlew test

      - name: Run integration tests
        run: ./gradlew intTest
